services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    hostname: db
    env_file:
      - ./api/.env
    volumes:
      - ./database-files:/docker-entrypoint-initdb.d/:ro
    ports:
      - "3200:3306"
    networks:
      - motivate-network

  api:
    build: ./api
    container_name: web-api
    hostname: web-api
    volumes:
      - ./api:/apicode
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - motivate-network

  app:
    build: ./app
    container_name: web-app
    hostname: web-app
    volumes:
      - ./app/src:/appcode
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - motivate-network

networks:
  motivate-network:
    driver: bridge
